// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import WaitlistController from "./waitlist_controller"
application.register("waitlist", WaitlistController)

import ClerkMountController from "./clerk_mount_controller"
application.register("clerk-mount", ClerkMountController)

import ClerkSignOutController from "./clerk_sign_out_controller"
application.register("clerk-sign-out", ClerkSignOutController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)
